### ISSUE TITLE
Miscellaneous ideas

### ISSUE THREAD

**Issue by sbj42** [mrsharpoblunto/foswig.js#18]
Here are some things I thought of while looking through the code.  Some of these are design decisions and breaking changes so I didn't want to go so far as to make pull requests for them.  This isn't really an "issue" but I don't know of a better way to communicate over github, so feel free to close this right away.

1. From 73e640c: "the API for this library is a bit whacky, generateWord should really should accept an options object", agreed.  See also the next item...
2. I'd like an option to specify my own random number generator.  Mainly this is so I can get reproducible results by seeding the generator.  I implemented this at https://github.com/sbj42/foswig.js/tree/custom-random as yet another argument, but if item 1 above is done then it would fit much better in the options object.
3. The current API allows the user to call addWordsToChain after calling generateWord.  This requires it to keep the `map` member around.  If the most common use case is to add all the words before generating any, then you can discard the map in between and save memory.  You could do this by having the caller pass all the source words in the constructor.  Not sure how much difference this would make.
4. It's possible that you could detect duplicates faster with a regular hash map rather than a trie.  It might depend on the length of the words and how often duplicates are generated.  Benchmarking would be necessary to be sure.  The hash map would also make it case-sensitive which may not be desired.  But it would simplify the code.
5. The duplication check is currently case-insensitive, but it does not take locale into account.  That might affect the generation of words in some other languages.  Since the Markov chain is case-sensitive, I'm not sure if case-insensitivity is necessary for the duplication check.  It might be simpler to just remove the toLowerCase calls, but I don't know what all the edge cases are.
6. There's an off-by-one issue with maxAttempts: the error check is `attempts >= maxAttempts`, so if there were exactly maxAttempts attempts, then it throws the error.  For instance, imagine if maxAttempts were 1.  I think this can be fixed by changing the check to `attempts >= maxAttempts && repeat`.  I didn't submit a PR for this because it's hard to make a test case for it without being able to seed the random number generator.

**Comment by pcnate** [comment]
I think it would be useful to show a list of the last few names that have been generated

**Comment by mrsharpoblunto** [comment]
Most of this is covered by the latest release including a better API, getting rid of the intermediate map, & allowing passing in a custom random generator
