### ISSUE TITLE
README is misleading about the third parameter of `generateWord()`

### ISSUE THREAD

**Issue by vincentbernat** [mrsharpoblunto/foswig.js#2]
README says that the last example is to generate a word that cannot be a match to any of the input dictionaries words but the third parameter is set to `true` which means allowing duplicates. The example should use `false`.

**Comment by mrsharpoblunto** [comment]
Thanks, I've updated the readme now. I really should change the library to pass in an options object containing all the optional fields. That would make the interface a bit cleaner and more in line with common JS library design - but thats a task for another day :)
